<p><h1>Numpy Assignment</h1></p>
<p><h2>Monthly Weather Analysis</h2></p>

<h3>Problem 1</h3>
Create and print a single numpy array and initialize it with random numbers  representing the temperature of a city for the month of June, July and august. The generated temps must be in the range of 28 to 50 degree celsius.


In [1]:
import numpy as np

In [2]:
# Generating random integers between 28 and 50 for each day of each month. Total 92 entries.
temp_june = np.random.randint(28, 51, 30)
temp_july = np.random.randint(28, 51, 31)
temp_august = np.random.randint(28, 51, 31)
temp = np.concatenate((temp_june, temp_july, temp_august), axis=0)     # Making a singular array
temp

array([39, 47, 38, 37, 47, 30, 47, 40, 50, 44, 43, 44, 36, 44, 45, 47, 49,
       43, 37, 49, 38, 41, 45, 48, 39, 33, 31, 49, 50, 32, 43, 32, 32, 50,
       47, 31, 28, 34, 38, 50, 45, 44, 42, 32, 45, 32, 38, 42, 49, 47, 43,
       31, 45, 32, 29, 33, 43, 46, 50, 45, 37, 31, 45, 35, 36, 50, 32, 35,
       41, 45, 38, 34, 41, 33, 38, 38, 48, 38, 31, 47, 33, 30, 29, 42, 47,
       39, 40, 30, 33, 47, 40, 30])

<h3>Problem 2</h3>
Calculate and print the avg, max and min temp of that city for entire time frame

In [3]:
print(f"avg = {temp.mean()}")
print(f"max = {temp.max()}")
print(f"min = {temp.min()}")

avg = 39.92391304347826
max = 50
min = 28


<h3>Problem 3</h3>
Calculate and print the avg, max and min temp of that city for each month

In [4]:
# Slicing the array monthwise.
avg_jun = temp[0:30].mean()
avg_jul = temp[30:61].mean()
avg_aug = temp[61:92].mean()
print(f"avg june = {avg_jun}")
print(f"avg july = {avg_jul}")
print(f"avg august = {avg_aug}")

avg june = 42.06666666666667
avg july = 39.83870967741935
avg august = 37.935483870967744


<h3>Problem 4</h3>
Calculate and print the amount with which the temp is rising or falling each day as compared to the previous day for all three months data.

In [23]:
# Storing the difference in temperature of the next day in an array. Total 91 entries.
difference = []

for i in range(len(temp)-1):
        diff = temp[i+1] - temp[i]
        difference.append(diff)

temp_difference = np.array(difference)
temp_difference

array([  8,  -9,  -1,  10, -17,  17,  -7,  10,  -6,  -1,   1,  -8,   8,
         1,   2,   2,  -6,  -6,  12, -11,   3,   4,   3,  -9,  -6,  -2,
        18,   1, -18,  11, -11,   0,  18,  -3, -16,  -3,   6,   4,  12,
        -5,  -1,  -2, -10,  13, -13,   6,   4,   7,  -2,  -4, -12,  14,
       -13,  -3,   4,  10,   3,   4,  -5,  -8,  -6,  14, -10,   1,  14,
       -18,   3,   6,   4,  -7,  -4,   7,  -8,   5,   0,  10, -10,  -7,
        16, -14,  -3,  -1,  13,   5,  -8,   1, -10,   3,  14,  -7, -10])

<h3>Problem 5</h3>
Calculate and print avg temp of each week



In [24]:
# Slicing the array for every 7 days. Last week has only 1 day.
number_of_weeks = int(np.ceil(len(temp)/7))

for i in range(number_of_weeks):
        week_avg = temp[i*7:(i*7)+7].mean()       #Using slicing to seperate out weeks
        print(f"avg week of {i+1} = {week_avg}")

avg week of 1 = 40.714285714285715
avg week of 2 = 43.0
avg week of 3 = 44.0
avg week of 4 = 40.857142857142854
avg week of 5 = 40.857142857142854
avg week of 6 = 38.57142857142857
avg week of 7 = 40.0
avg week of 8 = 37.142857142857146
avg week of 9 = 42.42857142857143
avg week of 10 = 39.142857142857146
avg week of 11 = 38.57142857142857
avg week of 12 = 35.714285714285715
avg week of 13 = 39.42857142857143
avg week of 14 = 30.0


<h3>Problem 6</h3>
Create a function that will take an input number from 1 to 7 as day of a week (1 for Sunday 7 for Sat) and print avg, max and min temp of the city on that day of the week over the complete 3 months.


In [25]:
# Assuming that 1st of June is a Sunday.
# I couldn't think of a shorter way to do this.
def day_week():
        user_day = int(input("Day? (1 to 7 : Sunday to Saturday)"))
        if user_day>7 or user_day<1:
                print("Invalid input.")
        else:
                index_day = user_day - 1
                day_temp = []

                if index_day == 0:     # Because we have 14 Sundays, and the rest of the days are only 13
                        for i in range(number_of_weeks):
                                day_temp.append(temp[i*7:(i*7)+7][index_day])     # Slicing the array for each week
                else:
                        for i in range(number_of_weeks-1):
                                day_temp.append(temp[i*7:(i*7)+7][index_day])

                print(f"avg of day {user_day} = {sum(day_temp)/len(day_temp)}")
                print(f"max of day {user_day} = {max(day_temp)}")
                print(f"min of day {user_day} = {min(day_temp)}")

        # ALTERNATE METHOD without slicing---

        # user_day = int(input("Day? (1 to 7 : Sunday to Saturday)"))
        # if user_day>7 or user_day<1:
        #         print("Invalid input.")
        # else:
        #         day = user_day
        #         day_temp = []

        #         if day == 1:
        #                 for i in range(number_of_weeks):
        #                         day_temp.append(temp[day-1])
        #                         day += 7
        #         else:
        #                 for i in range(number_of_weeks-1):
        #                         day_temp.append(temp[day-1])
        #                         day += 7

        #         print(f"avg of day {user_day} = {sum(day_temp)/len(day_temp)}")
        #         print(f"max of day {user_day} = {max(day_temp)}")
        #         print(f"min of day {user_day} = {min(day_temp)}")
day_week()

avg of day 5 = 37.38461538461539
max of day 5 = 50
min of day 5 = 30


<h3>Problem 7</h3>
Convert and print entire array from celsius to fahrenheit temp


In [26]:
# Numpy mathematical operations
temp_fahrenheit = (temp * 9)/5 + 32
temp_fahrenheit

array([102.2, 116.6, 100.4,  98.6, 116.6,  86. , 116.6, 104. , 122. ,
       111.2, 109.4, 111.2,  96.8, 111.2, 113. , 116.6, 120.2, 109.4,
        98.6, 120.2, 100.4, 105.8, 113. , 118.4, 102.2,  91.4,  87.8,
       120.2, 122. ,  89.6, 109.4,  89.6,  89.6, 122. , 116.6,  87.8,
        82.4,  93.2, 100.4, 122. , 113. , 111.2, 107.6,  89.6, 113. ,
        89.6, 100.4, 107.6, 120.2, 116.6, 109.4,  87.8, 113. ,  89.6,
        84.2,  91.4, 109.4, 114.8, 122. , 113. ,  98.6,  87.8, 113. ,
        95. ,  96.8, 122. ,  89.6,  95. , 105.8, 113. , 100.4,  93.2,
       105.8,  91.4, 100.4, 100.4, 118.4, 100.4,  87.8, 116.6,  91.4,
        86. ,  84.2, 107.6, 116.6, 102.2, 104. ,  86. ,  91.4, 116.6,
       104. ,  86. ])